#!/usr/bin/env bash

echo "API_HOST=$API_HOST" > .env
echo "API_KEY=$API_KEY" >> .env
echo "ENVIRONMENT=$ENVIRONMENT" >> .env
echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> .env
echo "ROLLBAR_API_KEY=$ROLLBAR_API_KEY" >> .env
echo "WEBSITE_HOST=$WEBSITE_HOST" >> .env

if [[ -n $PRODUCTION_API_HOST ]] ; then
  echo "PRODUCTION_API_HOST=$PRODUCTION_API_HOST" >> .env
fi

if [[ -n $PRODUCTION_API_KEY ]] ; then
  echo "PRODUCTION_API_KEY=$PRODUCTION_API_KEY" >> .env
fi

if [[ -n $PRODUCTION_ENVIRONMENT ]] ; then
  echo "PRODUCTION_ENVIRONMENT=$PRODUCTION_ENVIRONMENT" >> .env
fi

if [[ -n $PRODUCTION_GOOGLE_MAPS_API_KEY ]] ; then
  echo "PRODUCTION_GOOGLE_MAPS_API_KEY=$PRODUCTION_GOOGLE_MAPS_API_KEY" >> .env
fi

if [[ -n $PRODUCTION_ROLLBAR_API_KEY ]] ; then
  echo "PRODUCTION_ROLLBAR_API_KEY=$PRODUCTION_ROLLBAR_API_KEY" >> .env
fi

if [[ -n $PRODUCTION_WEBSITE_HOST ]] ; then
  echo "PRODUCTION_WEBSITE_HOST=$PRODUCTION_WEBSITE_HOST" >> .env
fi

if [[ -n $STAGING2_API_HOST ]] ; then
  echo "STAGING2_API_HOST=$STAGING2_API_HOST" >> .env
fi

if [[ -n $STAGING2_API_KEY ]] ; then
  echo "STAGING2_API_KEY=$STAGING2_API_KEY" >> .env
fi

if [[ -n $STAGING2_ENVIRONMENT ]] ; then
  echo "STAGING2_ENVIRONMENT=$STAGING2_ENVIRONMENT" >> .env
fi

if [[ -n $STAGING2_GOOGLE_MAPS_API_KEY ]] ; then
  echo "STAGING2_GOOGLE_MAPS_API_KEY=$STAGING2_GOOGLE_MAPS_API_KEY" >> .env
fi

if [[ -n $STAGING2_ROLLBAR_API_KEY ]] ; then
  echo "STAGING2_ROLLBAR_API_KEY=$STAGING2_ROLLBAR_API_KEY" >> .env
fi

if [[ -n $STAGING2_WEBSITE_HOST ]] ; then
  echo "STAGING2_WEBSITE_HOST=$STAGING2_WEBSITE_HOST" >> .env
fi
