# FPF change from true to fix crash in react-native-screens 4.6.0 / react native 0.76
# https://linear.app/front-porch-forum/issue/TECH-6504/update-to-react-native-076-and-update-mobile-packages#comment-e4f94056
# https://github.com/software-mansion/react-native-screens/issues/2339#issuecomment-2572502917
# https://reactnative.dev/architecture/landing-page#should-i-use-the-new-architecture-today
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1' # FPF setting
prepare_react_native_project!

# FPF addition -- Firebase
linkage = :static
# linkage = ENV['USE_FRAMEWORKS']
$RNFirebaseAsStaticFramework = true

if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FrontPorchForum' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
