# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1' # FPF setting
prepare_react_native_project!

# FPF addition -- Firebase
linkage = :static
# linkage = ENV['USE_FRAMEWORKS']
$RNFirebaseAsStaticFramework = true

if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FrontPorchForum' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix "Undefined symbols for architecture arm64" when building project
    # https://github.com/facebook/react-native/issues/31118#issuecomment-811881922
    # https://stackoverflow.com/a/63955114/154764
    installer.pods_project.build_configurations.each do |installer_config|
      installer_config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
