require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Detect AppCenter CI build
IS_CI = ENV['APPCENTER_BUILD_ID']

platform :ios, '11.0'

target 'FrontPorchForum' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper! unless IS_CI

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Fix "Undefined symbols for architecture arm64" when building project
    # https://github.com/facebook/react-native/issues/31118#issuecomment-811881922
    # https://stackoverflow.com/a/63955114/154764
    installer.pods_project.build_configurations.each do |installer_config|
      installer_config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
